// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzF7_zpR2qTpaArDGDhRlbavEfdrOpxX4',
    appId: '1:138047618205:web:462d2de1ca451838e3e874',
    messagingSenderId: '138047618205',
    projectId: 'smart-home-6da5a',
    authDomain: 'smart-home-6da5a.firebaseapp.com',
    databaseURL: 'https://smart-home-6da5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-6da5a.appspot.com',
    measurementId: 'G-98RZ6Q01ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3ABb3Fk67NSVys1AgTjI0ECFOs3GJkI',
    appId: '1:138047618205:android:375eff65c2ca74ade3e874',
    messagingSenderId: '138047618205',
    projectId: 'smart-home-6da5a',
    databaseURL: 'https://smart-home-6da5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-6da5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2FXe0JoxjWz_UvfvhLu5_Z3AIkR3arcQ',
    appId: '1:138047618205:ios:3e0f5b442c84c594e3e874',
    messagingSenderId: '138047618205',
    projectId: 'smart-home-6da5a',
    databaseURL: 'https://smart-home-6da5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-6da5a.appspot.com',
    iosBundleId: 'com.example.tubesSmartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2FXe0JoxjWz_UvfvhLu5_Z3AIkR3arcQ',
    appId: '1:138047618205:ios:4b54270811232cb2e3e874',
    messagingSenderId: '138047618205',
    projectId: 'smart-home-6da5a',
    databaseURL: 'https://smart-home-6da5a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-6da5a.appspot.com',
    iosBundleId: 'com.example.tubesSmartHome.RunnerTests',
  );
}
